### ISSUE TITLE
"Plug-in is incompatible  and requires author to update it"

### ISSUE THREAD

**Issue by conkincoding11** [equirs/fashionscape-plugin#66] opened 2024-01-25 21:15 UTC
As the title states, that is the message I get when I go to use the FashionScape (Best ever!) plug in. I frequently use this plug in to make content and can't wait to start using it again :)

**Comment by Popedigoz** [comment] 2024-01-26 03:07
+

**Comment by equirs** [comment] 2024-01-26 03:20
Dupe of https://github.com/equirs/fashionscape-plugin/issues/65

**Closed by equirs** 2024-01-26 03:20 UTC
